name: lint
on:
  push:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: install linters
      run: |
        sudo apt-get update
        sudo apt-get install -y lua-check
    - name: lint lua scripts
      run: ./lint.sh
